import pandas as pd
df = pd.read_csv("Age.csv")
# print(df)
# print(df.head())
# print(df.shape)
# print(df.info())
# print(df.describe())
# print(df["age"])
# print(df[["name","age"]])
# print(df.iloc[0])
# print(df.loc[0])
# print(df[df['age']>19])
# print(df[(df["age"] > 19) & (df["coures"] == "bca")])
# print(df.isnull())
# print(df.dropna())
# print(df.fillna(0))
# df["Salary"] = [10000,20000,30000,40000,50000]
# print(df.drop("Salary", axis=1, inplace=True))
# for index, row in df.iterrows():
#      print(row["Name"], row["Age"])
