import pandas as pd
df=pd.read_excel("FSI-2023-DOWNLOAD.xlsx")
# print(df)
# print(df.head())
# print(df.tail())
# print(df.shape)
# print(df.info())
# print(df.describe())
# print(df.columns)
# print(df.dtypes)
print(df["Year"])