import numpy123 as np
a = np.array([1,2,3,4])
print(type(a))
b = np.array([[1,2],[4,5]])
print(type(b))
c = np.array([[4,5],[7,8]])
# print(b+c)
# print(b-c)
# print(b*c)
# print(b/c)
# print(np.sqrt(b))
# print(np.multiply(b,c))
# print(b @ c)
# print(np.dot(b,c))
# print(b.T)
# print(np.min(c))
# print(np.max(b))
# print(np.mean(c))
# print(np.size(b))
# print(b.ndim)
# print(b.shape)
d = c.copy()
print(d)