import numpy123 as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[1,2])
print(arr[0,:2])
print(arr[:,1])
print(arr[1,:])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3))
print(np.full((2,2),7))
print(np.arange(0, 10, 2))
print(np.linspace(0,1,5))
print(np.random.rand(2,3))
print(np.random.randint(1,20,(2,3)))
for i in np.nditer(arr):
    print(i)
for i,v in enumerate(arr):
    print(f'index {i} and value {v}')